# Generated by Django 4.0 on 2021-12-26 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stratask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('time_expended', models.IntegerField(blank=True, null=True)),
                ('routine', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('to do ', 'TO DO'), ('doing', 'DOING'), ('done', 'DONE')], max_length=9)),
                ('importance', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True)),
                ('progress', models.IntegerField(blank=True, choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], null=True)),
                ('star', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stratask',
                'verbose_name_plural': 'Stratask',
            },
        ),
    ]
