# Generated by Django 4.0 on 2021-12-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stratask',
            name='importance',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='stratask',
            name='progress',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], max_length=200, null=True),
        ),
    ]
