# Generated by Django 4.0 on 2021-12-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startask', '0002_alter_stratask_importance_alter_stratask_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratask',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
